#!/usr/bin/env python3
"""Bake a pixel font (glyph art: "char X" then rows of '#' and '.') into a C
file defining a dgk_font_data: each glyph scaled up, with a one-pixel black
outline and a drop shadow, in cells of a power-of-two atlas. Pixel classes:
0 clear, 1 shadow, 2 outline, 3 ink (dgk_font_load turns them into RGBA).

  fontbake.py GLYPHS.txt OUT.c NAME [--scale 2] [--advance 13]
"""
import argparse


def read_glyphs(path):
    glyphs, name, rows = {}, None, []
    for line in open(path):
        line = line.rstrip("\n")
        if not line or line.startswith("#") and not set(line) <= {"#", "."}:
            continue
        if line.startswith("char "):
            if name is not None:
                glyphs[name] = rows
            tok = line[5:]
            name, rows = (" " if tok == "space" else tok), []
        else:
            rows.append(line)
    if name is not None:
        glyphs[name] = rows
    return glyphs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("glyphs")
    ap.add_argument("out")
    ap.add_argument("name")
    ap.add_argument("--scale", type=int, default=2)
    ap.add_argument("--advance", type=int, default=13)
    a = ap.parse_args()
    glyphs = read_glyphs(a.glyphs)
    gw = max(len(r) for g in glyphs.values() for r in g)
    gh = max(len(g) for g in glyphs.values())
    s = a.scale
    cell_w = 1 << (gw * s + 4 - 1).bit_length()         # ink + outline + shadow, rounded up
    cell_w = max(cell_w // 2 if cell_w // 2 >= gw * s + 4 else cell_w, gw * s + 4)
    cell_h = gh * s + 6
    cols = 16
    rows_needed = (len(glyphs) + cols - 1) // cols
    atlas_w = 1 << (cols * cell_w - 1).bit_length()
    atlas_h = 1 << (rows_needed * cell_h - 1).bit_length()
    px = [[0] * atlas_w for _ in range(atlas_h)]
    table = [-1] * 128
    for i, (ch, rows) in enumerate(sorted(glyphs.items(), key=lambda kv: ord(kv[0]))):
        ox, oy = (i % cols) * cell_w + 1, (i // cols) * cell_h + 1
        ink = set()
        for y, r in enumerate(rows):
            for x, c in enumerate(r):
                if c == "#":
                    for dy in range(s):
                        for dx in range(s):
                            ink.add((x * s + dx, y * s + dy))
        outline = {(x + dx, y + dy) for x, y in ink for dx in (-1, 0, 1) for dy in (-1, 0, 1)} - ink
        shape = ink | outline
        shadow = {(x + 2, y + 2) for x, y in shape} - shape
        for cls, pts in ((1, shadow), (2, outline), (3, ink)):
            for x, y in pts:
                if 0 <= ox + x < atlas_w and 0 <= oy + y < atlas_h:
                    px[oy + y][ox + x] = cls
        table[ord(ch)] = i
    with open(a.out, "w") as f:
        f.write("/* Generated by kit/tools/fontbake.py from %s: do not edit. */\n" % a.glyphs)
        f.write('#include "dgk/text.h"\n\n')
        f.write("static const uint8_t pixels[%d] = {\n" % (atlas_w * atlas_h))
        flat = [v for row in px for v in row]
        for i in range(0, len(flat), 64):
            f.write("    " + ",".join(str(v) for v in flat[i:i + 64]) + ",\n")
        f.write("};\n\n")
        f.write("const dgk_font_data %s = {\n" % a.name)
        f.write("    %d, %d, %d, %d, %d, pixels,\n" % (atlas_w, atlas_h, cell_w, cell_h, a.advance))
        f.write("    {" + ",".join(str(v) for v in table) + "}\n};\n")


if __name__ == "__main__":
    main()
